name: Run Securesystemslib tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    strategy:
      fail-fast: false
      # Run tests on each OS/Python combination
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        # TODO: Add windows-latest when gpg issues are solved
        os: [ubuntu-latest, macos-latest]
        toxenv: [py]

        include:
          - python-version: "3.11"
            os: ubuntu-latest
            toxenv: purepy311
          - python-version: "3.11"
            os: ubuntu-latest
            toxenv: py311-no-gpg
          - python-version: "3.11"
            os: ubuntu-latest
            toxenv: py311-test-gpg-fails
          - python-version: "3.11"
            os: ubuntu-latest
            toxenv: lint

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout securesystemslib
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@2c3dd9e7e29afd70cc0950079bde6c979d1f69f9
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements*.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox

      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}
