
name: Test GCP KMS

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    permissions:
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'

      - name: 'Sign with KMS key'
        run: |
          pip install google-cloud-kms
          python3 test-sign.py openssf global securesystemslib-test-keyring securesystemslib-test-key 1


