name: Run KMS tests

on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  test-kms:
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write' # for OIDC auth for GCP authentication

    steps:
      - name: Checkout securesystemslib
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72
        with:
          token_format: access_token
          workload_identity_provider: projects/843741030650/locations/global/workloadIdentityPools/securesystemslib-tests/providers/securesystemslib-tests
          service_account: securesystemslib-tests@python-tuf-kms.iam.gserviceaccount.com

      - run: tox -e kms
